/*
 *------------------------------------------------------------
 * Project:	cagOS
 * Goal:
 * Copyright (c) 2013, 2014 CAG Systems, Inc.
 *------------------------------------------------------------
 *
 *    @@@@     @@@      @@@@@       ####      ######
 *  @@       @@  @@    @@         ##    ##   ##
 * @@       @@    @@  @@   @@@@  ##      ## ######
 * @@      @@@@@@@@@@ @@    @@    ##    ##      ##
 *  @@@@@ @@@      @@@  @@@@@@      ####  #######
 *
 * The right to copy, distribute, modify or otherwise make use
 * of this software may be licensed only pursuant to the terms
 * of an applicable CAG license agreement.
 *
 * 1 tab == 4 spaces!
 *------------------------------------------------------------
 * modification history
 * --------------------
 * 03jun15,Jeff created
 *
 * DESCRIPTION
 * This file contains
 */

#ifndef __CONFIG_H__
#define __CONFIG_H__

#define  CLOCK_CFG_TASK_START_PRIO 0
#define  OS_CFG_STAT_TASK_PRIO    31
#define  APP_CFG_TASK_START_PRIO  5u
#define  OS_CFG_TASK_STK_LIMIT_PCT_EMPTY  10u

#define  OS_CFG_MSG_POOL_SIZE            100u               /* Maximum number of messages */ 

#define TASK_STACK_SIZE        0x00040000
#define TASK_SPESTACK_SIZE     0x00008000
#define TASK_SPESTACK_HIGH    (_CAG_START_TEXT + 0x01A00000)
#define TASK_SPESTACK_LOW     (_CAG_START_TEXT + 0x01900000)
#define TASK_STACK_HIGH       (_CAG_START_TEXT + 0x01900000)
#define TASK_STACK_LOW        (_CAG_START_TEXT + 0x01100000)
#define IRQ_STACK_HIGH        (_CAG_START_TEXT + 0x01100000)
#define IRQ_STACK_LOW         (_CAG_START_TEXT + 0x01000000)
#define EXC_STACK_HIGH        (_CAG_START_TEXT + 0x01000000)
#define EXC_STACK_LOW         (_CAG_START_TEXT + 0x00F00000)
#define DEC_STACK_HIGH        (_CAG_START_TEXT + 0x00F00000)
#define DEC_STACK_LOW         (_CAG_START_TEXT + 0x00E00000)
#define KERNEL_STACK_HIGH     (_CAG_START_TEXT + 0x00E00000)
#define KERNEL_STACK_LOW      (_CAG_START_TEXT + 0x00A00000)

#define TASK_STACK_MASK (TASK_STACK_SIZE-1)
#define TASK_STACK_0  (TASK_STACK_HIGH-(0*TASK_STACK_SIZE))
#define TASK_STACK_1  (TASK_STACK_HIGH-(1*TASK_STACK_SIZE))
#define TASK_STACK_2  (TASK_STACK_HIGH-(2*TASK_STACK_SIZE) )
#define TASK_STACK_3  (TASK_STACK_HIGH-(3*TASK_STACK_SIZE) )
#define TASK_STACK_4  (TASK_STACK_HIGH-(4*TASK_STACK_SIZE) )
#define TASK_STACK_5  (TASK_STACK_HIGH-(5*TASK_STACK_SIZE) )
#define TASK_STACK_6  (TASK_STACK_HIGH-(6*TASK_STACK_SIZE) )
#define TASK_STACK_7  (TASK_STACK_HIGH-(7*TASK_STACK_SIZE) )
#define TASK_STACK_8  (TASK_STACK_HIGH-(8*TASK_STACK_SIZE) )
#define TASK_STACK_9  (TASK_STACK_HIGH-(9*TASK_STACK_SIZE) )
#define TASK_STACK_10  (TASK_STACK_HIGH-(10*TASK_STACK_SIZE) )
#define TASK_STACK_11  (TASK_STACK_HIGH-(11*TASK_STACK_SIZE) )
#define TASK_STACK_12  (TASK_STACK_HIGH-(12*TASK_STACK_SIZE) )
#define TASK_STACK_13  (TASK_STACK_HIGH-(13*TASK_STACK_SIZE) )
#define TASK_STACK_14  (TASK_STACK_HIGH-(14*TASK_STACK_SIZE) )
#define TASK_STACK_15  (TASK_STACK_HIGH-(15*TASK_STACK_SIZE) )
#define TASK_STACK_16  (TASK_STACK_HIGH-(16*TASK_STACK_SIZE) )
#define TASK_STACK_17  (TASK_STACK_HIGH-(17*TASK_STACK_SIZE) )
#define TASK_STACK_18  (TASK_STACK_HIGH-(18*TASK_STACK_SIZE) )
#define TASK_STACK_19  (TASK_STACK_HIGH-(19*TASK_STACK_SIZE))
#define TASK_STACK_20  (TASK_STACK_HIGH-(20*TASK_STACK_SIZE))
#define TASK_STACK_21  (TASK_STACK_HIGH-(21*TASK_STACK_SIZE))
#define TASK_STACK_22  (TASK_STACK_HIGH-(22*TASK_STACK_SIZE))

#define TASK_STACK_23  (TASK_STACK_HIGH-(23*TASK_STACK_SIZE))
#define TASK_STACK_24  (TASK_STACK_HIGH-(24*TASK_STACK_SIZE))
#define TASK_STACK_25  (TASK_STACK_HIGH-(25*TASK_STACK_SIZE))
#define TASK_STACK_26  (TASK_STACK_HIGH-(26*TASK_STACK_SIZE))
#define TASK_STACK_27  (TASK_STACK_HIGH-(27*TASK_STACK_SIZE))
#define TASK_STACK_28  (TASK_STACK_HIGH-(28*TASK_STACK_SIZE))
#define TASK_STACK_29  (TASK_STACK_HIGH-(29*TASK_STACK_SIZE))
#define TASK_STACK_30  (TASK_STACK_HIGH-(30*TASK_STACK_SIZE))
#define TASK_STACK_31  (TASK_STACK_HIGH-(31*TASK_STACK_SIZE))

/* FOR SPE REGS OPS STACK */

#define TASK_SPESTACK_0  (TASK_SPESTACK_HIGH-(0*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_1  (TASK_SPESTACK_HIGH-(1*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_2  (TASK_SPESTACK_HIGH-(2*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_3  (TASK_SPESTACK_HIGH-(3*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_4  (TASK_SPESTACK_HIGH-(4*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_5  (TASK_SPESTACK_HIGH-(5*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_6  (TASK_SPESTACK_HIGH-(6*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_7  (TASK_SPESTACK_HIGH-(7*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_8  (TASK_SPESTACK_HIGH-(8*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_9  (TASK_SPESTACK_HIGH-(9*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_10  (TASK_SPESTACK_HIGH-(10*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_11  (TASK_SPESTACK_HIGH-(11*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_12  (TASK_SPESTACK_HIGH-(12*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_13  (TASK_SPESTACK_HIGH-(13*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_14  (TASK_SPESTACK_HIGH-(14*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_15  (TASK_SPESTACK_HIGH-(15*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_16  (TASK_SPESTACK_HIGH-(16*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_17  (TASK_SPESTACK_HIGH-(17*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_18  (TASK_SPESTACK_HIGH-(18*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_19  (TASK_SPESTACK_HIGH-(19*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_20  (TASK_SPESTACK_HIGH-(20*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_21  (TASK_SPESTACK_HIGH-(21*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_22  (TASK_SPESTACK_HIGH-(22*TASK_SPESTACK_SIZE))

#define TASK_SPESTACK_23  (TASK_SPESTACK_HIGH-(23*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_24  (TASK_SPESTACK_HIGH-(24*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_25  (TASK_SPESTACK_HIGH-(25*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_26  (TASK_SPESTACK_HIGH-(26*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_27  (TASK_SPESTACK_HIGH-(27*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_28  (TASK_SPESTACK_HIGH-(28*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_29  (TASK_SPESTACK_HIGH-(29*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_30  (TASK_SPESTACK_HIGH-(30*TASK_SPESTACK_SIZE))
#define TASK_SPESTACK_31  (TASK_SPESTACK_HIGH-(31*TASK_SPESTACK_SIZE))

#endif